# Setup
title: Show Us Your Sensors
tagline: It's kinda like bots gone wild
url: https://showusyoursensors.com
paginate: 5
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Michael Ferguson
  url: https://twitter.com/therealfergs
  github: mikeferguson

# Custom vars
version: 3.0.0